# This is the CI pipeline for the project.
# It will take care of things like dependency upgrades (ncu), testing, coverage (codecov, sonarcloud), builds, versioning and changelog (both standard-version)

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
